# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89d8d40fe5a9b30391cab601c0f30ee6522940aaa257aed60256305cbea4173812560da9ceecbd55255d11b18dfa7e9e34d982b2a8cfac4e7974ea336dd2cecb

test:
  secret_key_base: d1c5661dfb8cd0ba061ffab4c0c10fad89869b4042d9056f4ef7c8e7cb072e619f43b3d2201154f1d9b2de7e7137937cac9f74a641836e75c82cf121fff4977d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
