# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d39e6e064c47b126b11a1ad47bb5f87c4ba0ec659b8b42866f22ecb799f10042c28e31674c31804b4df7a120487df92fc9f34dd934892d43667a1371b909339

test:
  secret_key_base: 59d783869779406fb681c196296bf3429bf1193a4acd918d332f8486d95b37006a588845d106fcd969cd5016ceb6d2f0ad189a8dd30326bc9aa3a63eff154d2e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
