# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ab5dd6154e0847da0ff910279287052a4e8948a78708620c84cd94708a07d49535fb7469e4e63a1c46e420383e201aa2513f8465a89386326a665903066055b

test:
  secret_key_base: b4dc51770ef23628d42b59df67117e58959a1f0d16031b1da7d558308e06712ef24de70ec743e8ec86ade1d73832063fa0bd5524e3343ec7c9de630880c5c0f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
