# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c57a750287dc2a0254ed1a6af67beb9e699f5b2e38fe6e186fa5874af18c4f514d44edf4d613b2e17660a4cb7aae130f047c4b1d35c10c3901674d204d1d16b5

test:
  secret_key_base: 291265632b74b26552ea5115c588f8c04539d5a552d7e7902d0d6b5c0045019ab7fedbe89dd25a2483445dcbaa052f2ff55ad6e26da930b10e5cb5df1db30477

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
